# Generated by Django 4.1.4 on 2023-02-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_dale',
            new_name='birth_date',
        ),
    ]
