# Generated by Django 4.1.4 on 2023-01-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('horario', models.FloatField()),
                ('stock', models.BooleanField()),
            ],
        ),
    ]
