# Generated by Django 4.1.4 on 2023-01-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panaderia',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
