# Generated by Django 4.1.4 on 2023-01-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_panaderia_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
